from tkinter import *

def reset_face(canvas):
    canvas.delete(ALL)
    rectangle_1 = canvas.create_rectangle(60, 10, 150, 90, outline="#fb0", fill="#fb0")

def remove_face(canvas):
    canvas.delete(ALL)

def Draw(pending_guess,canvas):
    reset_face(canvas)

    if pending_guess == 9:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
    if pending_guess == 8:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
    if pending_guess == 7:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
    if pending_guess == 6:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
        canvas.create_text(80, 20, text="\\")
    if pending_guess == 5:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
        canvas.create_text(80, 20, text="\\")
        canvas.create_text(120, 20, text="/")
    if pending_guess == 4:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
        canvas.create_text(80, 20, text="\\")
        canvas.create_text(120, 20, text="/")
        canvas.create_text(80, 70, text="/")
    if pending_guess == 3:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
        canvas.create_text(80, 20, text="\\")
        canvas.create_text(120, 20, text="/")
        canvas.create_text(80, 70, text="/")
        canvas.create_text(120, 70, text="\\")
    if pending_guess == 2:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
        canvas.create_text(80, 20, text="\\")
        canvas.create_text(120, 20, text="/")
        canvas.create_text(80, 70, text="/")
        canvas.create_text(120, 70, text="\\")
        canvas.create_text(130, 20, text="|")
        canvas.create_text(130, 30, text="|")
    if pending_guess == 1:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
        canvas.create_text(80, 20, text="\\")
        canvas.create_text(120, 20, text="/")
        canvas.create_text(80, 70, text="/")
        canvas.create_text(120, 70, text="\\")
        canvas.create_text(130, 20, text="|")
        canvas.create_text(130, 30, text="|")
        canvas.create_text(110, 30, text="_")
        canvas.create_text(120, 30, text="_")
    if pending_guess == 0:
        canvas.create_text(70, 10, text="=")
        canvas.create_text(80, 10, text="=")
        canvas.create_text(90, 10, text="=")
        canvas.create_text(100, 10, text="=")
        canvas.create_text(110, 10, text="=")
        canvas.create_text(120, 10, text="=")
        canvas.create_text(130, 10, text="=")
        canvas.create_text(140, 10, text="=")
        canvas.create_text(100, 30, text="O")
        canvas.create_text(100, 40, text="|")
        canvas.create_text(100, 50, text="|")
        canvas.create_text(80, 70, text="/")
        canvas.create_text(120, 70, text="\\")
        canvas.create_text(130, 20, text="|")
        canvas.create_text(130, 30, text="|")
        canvas.create_text(110, 30, text="_")
        canvas.create_text(120, 30, text="_")
        canvas.create_text(90, 40, text="/")
        canvas.create_text(110, 40, text="\\")