def words():
    return {"tokyo" : "Japan",
            "jakarta" : "Indonesia",
            "new york" : "United States",
            "seoul" : "South Korea",
            "manila" : "Philippines",
            "mumbai" : "India",
            "sao paulo" : "Brazil",
            "mexico city" : "Mexico",
            "delhi" : "India",
            "osaka" : "Japan",
            "cairo" : "Egypt",
            "kolkata" : "India",
            "los angeles" : "United States",
            "shanghai" : "China",
            "moscow" : "Russia",
            "beijing" : "China",
            "buenos aires" : "Argentina",
            "guangzhou" : "China",
            "shenzhen" : "China",
            "istanbul" : "Turkey",
            "rio de janeiro" : "Brazil",
            "paris" : "France",
            "karachi" : "Pakistan",
            "nagoya" : "Japan",
            "chicago" : "United States",
            "lagos" : "Nigeria",
            "london" : "United Kingdom",
            "bangkok" : "Thailand",
            "kinshasa" : "Dem Rep of Congo",
            "tehran" : "Iran",
            "lima" : "Peru",
            "dongguan" : "China",
            "bogota" : "Colombia",
            "chennai" : "India",
            "dhaka" : "Bangladesh",
            "essen" : "Germany",
            "tianjin" : "China",
            "hong kong" : "China - Hong Kong",
            "taipei" : "Taiwan (China ROC)",
            "lahore" : "Pakistan",
            "ho chi minh city" : "Viet Nam",
            "bangalore" : "India",
            "hyderabad" : "India",
            "johannesburg" : "South Africa",
            "baghdad" : "Iraq",
            "toronto" : "Canada",
            "santiago" : "Chile",
            "kuala lumpur" : "Malaysia",
            "san francisco" : "United States",
            "philadelphia" : "United States",
            "wuhan" : "China",
            "miami" : "United States",
            "dallas" : "United States",
            "madrid" : "Spain",
            "ahmedabad" : "India",
            "boston" : "United States",
            "belo horizonte" : "Brazil",
            "khartoum" : "Sudan",
            "saint petersburg" : "Russia",
            "shenyang" : "China",
            "houston" : "United States",
            "pune" : "India",
            "riyadh" : "Saudi Arabia",
            "singapore" : "Singapore",
            "washington" : "United States",
            "yangon" : "Myanmar",
            "milan" : "Italy",
            "atlanta" : "United States",
            "chongqing" : "China",
            "alexandria" : "Egypt",
            "nanjing" : "China",
            "guadalajara" : "Mexico",
            "barcelona" : "Spain",
            "chengdu" : "China",
            "detroit" : "United States",
            "ankara" : "Turkey",
            "abidjan" : "Côte d'Ivoire",
            "athens" : "Greece",
            "berlin" : "Germany",
            "sydney" : "Australia",
            "monterrey" : "Mexico",
            "phoenix" : "United States",
            "busan" : "South Korea",
            "recife" : "Brazil",
            "bandung" : "Indonesia",
            "porto alegre" : "Brazil",
            "melbourne" : "Australia",
            "luanda" : "Angola",
            "hangzhou" : "China",
            "algiers" : "Algeria",
            "hanoi" : "Viet Nam",
            "montreal" : "Canada",
            "pyongyang" : "North Korea",
            "qingdao" : "China",
            "surat" : "India",
            "fortaleza" : "Brazil",
            "medellã­n" : "Colombia",
            "durban" : "South Africa",
            "kanpur" : "India",
            "addis ababa" : "Ethiopia",
            "nairobi" : "Kenya",
            "jeddah" : "Saudi Arabia",
            "naples" : "Italy",
            "kabul" : "Afghanistan",
            "salvador" : "Brazil",
            "harbin" : "China",
            "kano" : "Nigeria",
            "casablanca" : "Morocco",
            "cape town" : "South Africa",
            "curitiba" : "Brazil",
            "surabaya" : "Indonesia",
            "san diego" : "United States",
            "seattle" : "United States",
            "rome" : "Italy",
            "dar es salaam" : "Tanzania",
            "taichung" : "China",
            "jaipur" : "India",
            "caracas" : "Venezuela",
            "dakar" : "Senegal",
            "kaohsiung" : "China",
            "minneapolis" : "United States",
            "lucknow" : "India",
            "amman" : "Jordan",
            "guayaquil" : "Ecuador",
            "kyiv" : "Ukraine",
            "faisalabad" : "Pakistan",
            "mashhad" : "Iran",
            "izmir" : "Turkey",
            "rawalpindi" : "Pakistan",
            "tashkent" : "Uzbekistan",
            "katowice" : "Poland",
            "changchun" : "China",
            "campinas" : "Brazil",
            "daegu" : "South Korea",
            "changsha" : "China",
            "nagpur" : "India",
            "san juan" : "Philippines",
            "aleppo" : "Syria",
            "lisbon" : "Portugal",
            "frankfurt am main" : "Germany",
            "nanchang" : "China",
            "birmingham" : "United Kingdom",
            "tampa" : "United States",
            "medan" : "Indonesia",
            "dalian" : "China",
            "tunis" : "Tunisia",
            "shijiazhuang" : "China",
            "manchester" : "United Kingdom",
            "damascus" : "Syria",
            "fukuoka" : "Japan",
            "santo domingo" : "Dominican Republic",
            "havana" : "Cuba",
            "cali" : "Colombia",
            "denver" : "United States",
            "colombo" : "Brazil",
            "dubai" : "United Arab Emirates",
            "baltimore" : "United States",
            "sapporo" : "Japan",
            "rotterdam" : "Netherlands",
            "vancouver" : "Canada",
            "preston" : "United Kingdom",
            "patna" : "India",
            "warsaw" : "Poland",
            "bonn" : "Germany",
            "accra" : "Ghana",
            "bucharest" : "Romania",
            "yokohama" : "Japan",
            "kunming" : "China",
            "guiyang" : "China",
            "zibo" : "China",
            "incheon" : "South Korea",
            "zhengzhou" : "China",
            "taiyuan" : "China",
            "chaoyang" : "China",
            "brasilia" : "Brazil",
            "zhongshan" : "China",
            "west midlands" : "United Kingdom",
            "giza" : "Egypt",
            "quezon city" : "Philippines",
            "nanhai" : "China",
            "fuzhou" : "China",
            "lanzhou" : "China",
            "xiamen" : "China",
            "chittagong" : "Bangladesh",
            "zaozhuang" : "China",
            "jilin" : "China",
            "linyi" : "China",
            "wenzhou" : "China",
            "stockholm" : "Sweden",
            "puebla de zaragoza" : "Mexico",
            "puning" : "China",
            "baku" : "Azerbaijan",
            "ibadan" : "Nigeria",
            "brisbane" : "Australia",
            "minsk" : "Belarus",
            "sikasso" : "Mali",
            "nanchong" : "China",
            "nanning" : "China",
            "urumqi" : "China",
            "yantai" : "China",
            "fuyang" : "China",
            "tangshan" : "China",
            "maracaibo" : "Venezuela",
            "hamburg" : "Germany",
            "budapest" : "Hungary",
            "shunde" : "China",
            "manaus" : "Brazil",
            "xuzhou" : "China",
            "baotou" : "China",
            "hefei" : "China",
            "vienna" : "Austria",
            "indore" : "India",
            "asuncion" : "Paraguay",
            "tianmen" : "China",
            "belgrade" : "Serbia",
            "suzhou" : "China",
            "suizhou" : "China",
            "nanyang" : "China",
            "nakuru" : "Kenya",
            "koulikoro" : "Mali",
            "ningbo" : "China",
            "liuan" : "China",
            "anshan" : "China",
            "tengzhou" : "China",
            "qiqihaer" : "China",
            "pizhou" : "China",
            "taian" : "China",
            "datong" : "China",
            "kobe" : "Japan",
            "hama" : "Syria",
            "esfahan" : "Iran",
            "tripoli" : "Libya",
            "west yorkshire" : "United Kingdom",
            "vadodara" : "India",
            "taizhou" : "China",
            "luoyang" : "China",
            "quito" : "Ecuador",
            "jinjiang" : "China",
            "mopti" : "Mali",
            "perth" : "Australia",
            "daejeon" : "South Korea",
            "kyoto" : "Japan",
            "xiantao" : "China",
            "tangerang" : "Indonesia",
            "bhopal" : "India",
            "coimbatore" : "India",
            "kharkiv" : "Ukraine",
            "gwangju" : "South Korea",
            "xinghua" : "China",
            "harare" : "Zimbabwe",
            "fushun" : "China",
            "shangqiu" : "China",
            "wuxi" : "China",
            "hechuan" : "China",
            "wujin" : "China",
            "guigang" : "China",
            "jianyang" : "China",
            "huhehaote" : "China",
            "santa cruz" : "Bolivia",
            "semarang" : "Indonesia",
            "ludhiana" : "India",
            "novosibirsk" : "Russia",
            "neijiang" : "China",
            "maputo" : "Mozambique",
            "douala" : "Cameroon",
            "weifang" : "China",
            "daqing" : "China",
            "kayes" : "Mali",
            "tongzhou" : "China",
            "tabriz" : "Iran",
            "homs" : "Syria",
            "rugao" : "China",
            "guiping" : "China",
            "huainan" : "China",
            "kochi" : "India",
            "suining" : "China",
            "bozhou" : "China",
            "zhanjiang" : "China",
            "changde" : "China",
            "montevideo" : "Uruguay",
            "suzhou" : "China",
            "xintai" : "China",
            "ekaterinoburg" : "Russia",
            "juarez" : "Mexico",
            "handan" : "China",
            "visakhapatnam" : "India",
            "kawasaki" : "Japan",
            "jiangjin" : "China",
            "pingdu" : "China",
            "agra" : "India",
            "jiangyin" : "China",
            "tijuana" : "Mexico",
            "liuyang" : "China",
            "bursa" : "Turkey",
            "makkah" : "Saudi Arabia",
            "yaounde" : "Cameroon",
            "xuanwei" : "China",
            "dengzhou" : "China",
            "palembang" : "Indonesia",
            "nizhny novgorod" : "Russia",
            "leon" : "Mexico",
            "guarulhos" : "Brazil",
            "heze" : "China",
            "auckland" : "New Zealand",
            "omdurman" : "Sudan",
            "shantou" : "China",
            "leizhou" : "China",
            "yongcheng" : "China",
            "valencia" : "Venezuela",
            "thane" : "India",
            "san antonio" : "United States",
            "xinyang" : "China",
            "luzhou" : "China",
            "almaty" : "Kazakhstan",
            "changshu" : "China",
            "taixing" : "China",
            "phnom penh" : "Cambodia",
            "laiwu" : "China",
            "xiaoshan" : "China",
            "yiyang" : "China",
            "liuzhou" : "China",
            "gaozhou" : "China",
            "fengcheng" : "China",
            "cixi" : "China",
            "karaj" : "Iran",
            "mogadishu" : "Somalia",
            "varanasi" : "India",
            "cordoba" : "Argentina",
            "kampala" : "Uganda",
            "ruian" : "China",
            "lianjiang" : "China",
            "huaian" : "China",
            "shiraz" : "Iran",
            "multan" : "Pakistan",
            "madurai" : "India",
            "munich" : "Germany",
            "kalyan" : "India",
            "quanzhou" : "China",
            "adana" : "Turkey",
            "bazhong" : "China",
            "ouagadougou" : "Burkina Faso",
            "haicheng" : "China",
            "xishan" : "China",
            "leiyang" : "China",
            "caloocan" : "Philippines",
            "kalookan" : "Philippines",
            "jingzhou" : "China",
            "saitama" : "Japan",
            "prague" : "Czech Republic",
            "fuqing" : "China",
            "kumasi" : "Ghana",
            "meerut" : "India",
            "hyderabad" : "Pakistan",
            "lufeng" : "China",
            "dongtai" : "China",
            "yixing" : "China",
            "mianyang" : "China",
            "wenling" : "China",
            "leqing" : "China",
            "ottawa" : "Canada",
            "yushu" : "China",
            "barranquilla" : "Colombia",
            "hiroshima" : "Japan",
            "chifeng" : "China",
            "nashik" : "India",
            "makasar" : "Indonesia",
            "sofia" : "Bulgaria",
            "rizhao" : "China",
            "davao" : "Philippines",
            "tianshui" : "China",
            "huzhou" : "China",
            "samara" : "Russia",
            "omsk" : "Russia",
            "gujranwala" : "Pakistan",
            "adelaide" : "Australia",
            "macheng" : "China",
            "wuxian" : "China",
            "bijie" : "China",
            "yuzhou" : "China",
            "leshan" : "China",
            "la matanza" : "Argentina",
            "rosario" : "Argentina",
            "jabalpur" : "India",
            "kazan" : "Russia",
            "jimo" : "China",
            "dingzhou" : "China",
            "calgary" : "Canada",
            "yerevan" : "Armenia",
            "jamshedpur" : "India",
            "zurich" : "Switzerland",
            "zoucheng" : "China",
            "anqiu" : "China",
            "chelyabinsk" : "Russia",
            "conakry" : "Guinea",
            "asansol" : "India",
            "shouguang" : "China",
            "changzhou" : "China",
            "ulsan" : "South Korea",
            "zhuji" : "China",
            "toluca" : "Mexico",
            "marrakech" : "Morocco",
            "dhanbad" : "India",
            "tbilisi" : "Georgia",
            "hanchuan" : "China",
            "lusaka" : "Zambia",
            "qidong" : "China",
            "faridabad" : "India",
            "zaoyang" : "China",
            "zhucheng" : "China",
            "jiangdu" : "China",
            "xiangcheng" : "China",
            "zigong" : "China",
            "jining" : "China",
            "edmonton" : "Canada",
            "allahabad" : "India",
            "beiliu" : "China",
            "dnipropetrovsk" : "Ukraine",
            "gongzhuling" : "China",
            "qinzhou" : "China",
            "ufa" : "Russia",
            "sendai" : "Japan",
            "volgograd" : "Russia",
            "ezhou" : "China",
            "guatemala city" : "Guatemala",
            "zhongxiang" : "China",
            "amsterdam" : "Netherlands",
            "brussels" : "Belgium",
            "bamako" : "Mali",
            "ziyang" : "China",
            "antananarivo" : "Madagascar",
            "mudanjiang" : "China",
            "amritsar" : "India",
            "vijayawada" : "India",
            "haora" : "India",
            "donetsk" : "Ukraine",
            "huazhou" : "China",
            "fuzhou" : "China",
            "pimpri chinchwad" : "India",
            "dublin" : "Ireland",
            "rajkot" : "India",
            "sao luã­s" : "Brazil",
            "lianyuan" : "China",
            "liupanshui" : "China",
            "kaduna" : "Nigeria",
            "kitakyushu" : "Japan",
            "qianjiang" : "China",
            "perm" : "Russia",
            "odessa" : "Ukraine",
            "qom" : "Iran",
            "yongchuan" : "China",
            "peshawar" : "Pakistan",
            "linzhou" : "China",
            "benxi" : "China",
            "ulaanbaatar" : "Mongolia",
            "zhangqiu" : "China",
            "yongzhou" : "China",
            "sao gonã§alo" : "Brazil",
            "srinagar" : "India",
            "ghaziabad" : "India",
            "xinyi" : "China",
            "koln" : "Germany",
            "zhangjiagang" : "China",
            "wafangdian" : "China",
            "xianyang" : "China",
            "liaocheng" : "China",
            "ahwaz" : "Iran",
            "taishan" : "China",
            "linhai" : "China",
            "feicheng" : "China",
            "suwon" : "South Korea",
            "wuwei" : "China",
            "haimen" : "China",
            "san luis potosã­" : "Mexico",
            "liling" : "China",
            "xinhui" : "China",
            "gaziantep" : "Turkey",
            "krasnoyarsk" : "Russia",
            "chiba" : "Japan",
            "voronezh" : "Russia",
            "ruzhou" : "China",
            "maceio" : "Brazil",
            "yichun" : "China",
            "yulin" : "China",
            "seongnam" : "South Korea",
            "yueyang" : "China",
            "yiwu" : "China",
            "san jose" : "United States",
            "jixi" : "China",
            "managua" : "Nicaragua",
            "xinyi" : "China",
            "safi" : "Morocco",
            "guangyuan" : "China",
            "soweto" : "South Africa",
            "zhangjiakou" : "China",
            "baoding" : "China",
            "cartagena" : "Colombia",
            "huludao" : "China",
            "pingdingshan" : "China",
            "torino" : "Italy",
            "zengcheng" : "China",
            "laiyang" : "China",
            "qingzhou" : "China",
            "aurangabad" : "India",
            "lattakia" : "Syria",
            "laizhou" : "China",
            "thiruvananthapuram" : "India",
            "weinan" : "China",
            "wuchang" : "China",
            "guangshui" : "China",
            "gaizhou" : "China",
            "goteborg" : "Sweden",
            "xiaogan" : "China",
            "torreon" : "Mexico",
            "jiaxing" : "China",
            "kozhikode" : "India",
            "zhuzhou" : "China",
            "tyneside" : "United Kingdom",
            "hengyang" : "China",
            "dehui" : "China",
            "honghu" : "China",
            "danyang" : "China",
            "daye" : "China",
            "solapur" : "India",
            "xingning" : "China",
            "xiangfan" : "China",
            "luoding" : "China",
            "gwalior" : "India",
            "ranchi" : "India",
            "huiyang" : "China",
            "mombasa" : "Kenya",
            "jinzhou" : "China",
            "jiangyan" : "China",
            "chenghai" : "China",
            "jiamusi" : "China",
            "songzi" : "China",
            "tegucigalpa" : "Honduras",
            "wujiang" : "China",
            "jodhpur" : "India",
            "duque de caxias" : "Brazil",
            "yuyao" : "China",
            "hezhou" : "China",
            "jiangyou" : "China",
            "tiruchchirappalli" : "India",
            "baoshan" : "China",
            "saratov" : "Russia",
            "nova iguaã§u" : "Brazil",
            "ankang" : "China",
            "gaomi" : "China",
            "yangchun" : "China",
            "santiago de los caballeros" : "Dominican Republic",
            "danzhou" : "China",
            "la paz" : "Bolivia",
            "zhuanghe" : "China",
            "zhuhai" : "China",
            "zhaodong" : "China",
            "sakai" : "Japan",
            "haikou" : "China",
            "jiaonan" : "China",
            "el alto" : "Bolivia",
            "xuancheng" : "China",
            "wuchuan" : "China",
            "yuhang" : "China",
            "qinhuangdao" : "China",
            "bogor" : "Indonesia",
            "kermanshah" : "Iran",
            "longhai" : "China",
            "liverpool" : "United Kingdom",
            "yanshi" : "China",
            "guwahati" : "India",
            "yichun" : "China",
            "konya" : "Turkey",
            "barquisimeto" : "Venezuela",
            "yingde" : "China",
            "bengbu" : "China",
            "yibin" : "China",
            "chandigarh" : "India",
            "xiangxiang" : "China",
            "yinchuan" : "China",
            "valencia" : "Spain",
            "guilin" : "China",
            "hamamatsu" : "Japan",
            "sao bernardo do campo" : "Brazil",
            "bishkek" : "Kyrgyzstan",
            "teresina" : "Brazil",
            "suihua" : "China",
            "benghazi" : "Libya",
            "jiutai" : "China",
            "meishan" : "China",
            "zaporizhya" : "Ukraine",
            "gaoyou" : "China",
            "marseille" : "France",
            "kaifeng" : "China",
            "changning" : "China",
            "tongliao" : "China",
            "natal" : "Brazil",
            "bandar lampung" : "Indonesia",
            "dongying" : "China",
            "gaoan" : "China",
            "langzhong" : "China",
            "lichuan" : "China",
            "mysore" : "India",
            "niigata" : "Japan",
            "indianapolis" : "United States",
            "jiaozhou" : "China",
            "pingxiang" : "China",
            "haiphong" : "Viet Nam",
            "arequipa" : "Peru",
            "jacksonville" : "United States",
            "tanger" : "Morocco",
            "dandong" : "China",
            "kishinev" : "Moldova",
            "krasnodar" : "Russia",
            "zagreb" : "Croatia",
            "xinmi" : "China",
            "chaohu" : "China",
            "xinyu" : "China",
            "gongyi" : "China",
            "huixian" : "China",
            "xinxiang" : "China",
            "port elizabeth" : "South Africa",
            "mendoza" : "Argentina",
            "nantong" : "China",
            "pengzhou" : "China",
            "khulna" : "Bangladesh",
            "malang" : "Indonesia",
            "padang" : "Indonesia",
            "anyang" : "China",
            "renqiu" : "China",
            "foshan" : "China",
            "anshun" : "China",
            "chihuahua" : "Mexico",
            "campo grande" : "Brazil",
            "lodz" : "Poland",
            "goyang" : "South Korea",
            "benin city" : "Nigeria",
            "bucheon" : "South Korea",
            "gaocheng" : "China",
            "pulandian" : "China",
            "hejian" : "China",
            "dafeng" : "China",
            "krakow" : "Poland",
            "enshi" : "China",
            "dongyang" : "China",
            "lviv" : "Ukraine",
            "kunshan" : "China",
            "shuangcheng" : "China",
            "salem" : "India",
            "jiaozuo" : "China",
            "huaibei" : "China",
            "liyang" : "China",
            "samut prakan" : "Thailand",
            "rongcheng" : "China",
            "cenxi" : "China",
            "nampho" : "North Korea",
            "columbus" : "United States",
            "bareilly" : "India",
            "leping" : "China",
            "laixi" : "China",
            "liaoyang" : "China",
            "zhaotong" : "China",
            "jerusalem" : "Israel",
            "tainan" : "China",
            "cuernavaca" : "Mexico",
            "riga" : "Latvia",
            "linfen" : "China",
            "lingbao" : "China",
            "shangyu" : "China",
            "wuan" : "China",
            "hailun" : "China",
            "xingyi" : "China",
            "wuxue" : "China",
            "cebu" : "Philippines",
            "aguascalientes" : "Mexico",
            "tolyatti" : "Russia",
            "hamilton" : "Canada",
            "zhoushan" : "China",
            "langfang" : "China",
            "osasco" : "Brazil",
            "nonthaburi" : "Thailand",
            "dashiqiao" : "China",
            "tongxiang" : "China",
            "yichang" : "China",
            "yangzhou" : "China",
            "blantyre city" : "Malawi",
            "hamhung" : "North Korea",
            "jalandhar" : "India",
            "niamey" : "Niger",
            "xiangtan" : "China",
            "winnipeg" : "Canada",
            "oran" : "Algeria",
            "kota" : "India",
            "sevilla" : "Spain",
            "navi mumbai" : "India",
            "port harcourt" : "Nigeria",
            "saltillo" : "Mexico",
            "khartoum north" : "Sudan",
            "shizuoka" : "Japan",
            "yuanjiang" : "China",
            "raipur" : "India",
            "kryviy rig" : "Ukraine",
            "yingkou" : "China",
            "wuhu" : "China",
            "zhenjiang" : "China",
            "nankang" : "China",
            "wugang" : "China",
            "hegang" : "China",
            "linqing" : "China",
            "pretoria" : "South Africa",
            "zunyi" : "China",
            "panzhihua" : "China",
            "austin" : "United States",
            "changle" : "China",
            "lianyungang" : "China",
            "yancheng" : "China",
            "zunhua" : "China",
            "changyi" : "China",
            "qiongshan" : "China",
            "bulawayo" : "Zimbabwe",
            "wendeng" : "China",
            "okayama" : "Japan",
            "rabat" : "Morocco",
            "pakanbaru" : "Indonesia",
            "nehe" : "China",
            "memphis" : "United States",
            "joao pessoa" : "Brazil",
            "kathmandu" : "Nepal",
            "longkou" : "China",
            "shengzhou" : "China",
            "antalya" : "Turkey",
            "kumamoto" : "Japan",
            "lilongwe" : "Malawi",
            "mexicali" : "Mexico",
            "kaiping" : "China",
            "palermo" : "Italy",
            "aligarh" : "India",
            "nottingham" : "United Kingdom",
            "haining" : "China",
            "mosul" : "Iraq",
            "hermosillo" : "Mexico",
            "tongcheng" : "China",
            "shulan" : "China",
            "miluo" : "China",
            "bhubaneswar" : "India",
            "yangquan" : "China",
            "chenzhou" : "China",
            "haiyang" : "China",
            "morelia" : "Mexico",
            "huangshi" : "China",
            "xinmin" : "China",
            "barnaul" : "Russia",
            "qixia" : "China",
            "jaboatao dos guarapes" : "Brazil",
            "chongzhou" : "China",
            "cotonou" : "Benin",
            "yingcheng" : "China",
            "zaragoza" : "Spain",
            "changzhi" : "China",
            "qujing" : "China",
            "linghai" : "China",
            "changge" : "China",
            "trujillo" : "Peru",
            "tampico" : "Mexico",
            "maoming" : "China",
            "moron" : "Argentina",
            "la plata" : "Argentina",
            "ciudad guayana" : "Venezuela",
            "moradabad" : "India",
            "jieshou" : "China",
            "sheffield" : "United Kingdom",
            "donggang" : "China",
            "jingjiang" : "China",
            "acheng" : "China",
            "acapulco" : "Mexico",
            "veracruz" : "Mexico",
            "ulyanovsk" : "Russia",
            "wroclaw" : "Poland",
            "jieyang" : "China",
            "shaoxing" : "China",
            "nanchuan" : "China",
            "qionglai" : "China",
            "deyang" : "China",
            "sagamihara" : "Japan",
            "fuyang" : "China",
            "fuxin" : "China",
            "jiyuan" : "China",
            "puente alto" : "Chile",
            "qufu" : "China",
            "gaoyao" : "China",
            "gorakhpur" : "India",
            "fort worth" : "United States",
            "xinji" : "China",
            "dujiangyan" : "China",
            "the hague" : "Netherlands",
            "bhiwandi" : "India",
            "lingyuan" : "China",
            "xingyang" : "China",
            "maiduguri" : "Nigeria",
            "genova" : "Italy",
            "meihekou" : "China",
            "izhevsk" : "Russia",
            "jeonju" : "South Korea",
            "leling" : "China",
            "xichang" : "China",
            "colombo" : "Sri Lanka",
            "zaria" : "Nigeria",
            "anlu" : "China",
            "charlotte" : "United States",
            "yizheng" : "China",
            "malmo" : "Sweden",
            "weihai" : "China",
            "xinzheng" : "China",
            "dengfeng" : "China",
            "vladivostok" : "Russia",
            "shaoyang" : "China",
            "taizhou" : "China",
            "jammu" : "India",
            "lanxi" : "China",
            "yuncheng" : "China",
            "kagoshima" : "Japan",
            "yaroslave" : "Russia",
            "contagem" : "Brazil",
            "shishou" : "China",
            "panjin" : "China",
            "zamboanga" : "Philippines",
            "orumiyeh" : "Iran",
            "binzhou" : "China",
            "kisumu" : "Kenya",
            "baoji" : "China",
            "el paso" : "United States",
            "yunzhou" : "China",
            "diyarbakir" : "Turkey",
            "jurong" : "China",
            "cãºcuta" : "Colombia",
            "zhaoyuan" : "China",
            "huizhou" : "China",
            "tianchang" : "China",
            "dortmund" : "Germany",
            "shihezi" : "China",
            "shiyan" : "China",
            "cuttack" : "India",
            "cochabamba" : "Bolivia",
            "cheongju" : "South Korea",
            "jingmen" : "China",
            "shangzhi" : "China",
            "anqing" : "China",
            "chongjin" : "North Korea",
            "stuttgart" : "Germany",
            "rushan" : "China",
            "kingston" : "Jamaica",
            "milwaukee" : "United States",
            "sorocaba" : "Brazil",
            "glasgow" : "United Kingdom",
            "khabarovsk" : "Russia",
            "guanghan" : "China",
            "warangal" : "India",
            "irkutsk" : "Russia",
            "tyumen" : "Russia",
            "lomas de zamora" : "Argentina",
            "beipiao" : "China",
            "funabashi" : "Japan",
            "mingguang" : "China",
            "dusseldorf" : "Germany",
            "shenzhou" : "China",
            "iã§el" : "Turkey",
            "zhangzhou" : "China",
            "xianning" : "China",
            "maanshan" : "China",
            "bandjarmasin" : "Indonesia",
            "callao" : "Peru",
            "poznan" : "Poland",
            "kayseri" : "Turkey",
            "chon buri" : "Thailand",
            "quetta" : "Pakistan",
            "shuozhou" : "China",
            "samarinda" : "Indonesia",
            "helsinki" : "Finland",
            "akesu" : "China",
            "novokuznetsk" : "Russia",
            "malaga" : "Spain",
            "fengcheng" : "China",
            "hachioji" : "Japan",
            "ribeirao prãªto" : "Brazil",
            "beihai" : "China",
            "jamnagar" : "India",
            "nouakchott" : "Mauritania",
            "bazhou" : "China",
            "yongkang" : "China",
            "louisville" : "United States",
            "chizhou" : "China",
            "huaiyin" : "China",
            "fuan" : "China",
            "bhilai nagar" : "India",
            "dezhou" : "China",
            "makhachkala" : "Russia",
            "xingping" : "China",
            "jiujiang" : "China",
            "bristol" : "United Kingdom",
            "botou" : "China",
            "fengnan" : "China",
            "astana" : "Kazakhstan",
            "yizhou" : "China",
            "amravati" : "India",
            "batam" : "Indonesia",
            "orenburg" : "Russia",
            "zhuozhou" : "China",
            "las vegas" : "United States",
            "cancun" : "Mexico",
            "longyan" : "China",
            "oslo" : "Norway",
            "tiruppur" : "India",
            "vilnius" : "Lithuania",
            "bremen" : "Germany",
            "gaobeidian" : "China",
            "mangalore" : "India",
            "songyuan" : "China",
            "yangjiang" : "China",
            "wanyuan" : "China",
            "jiangmen" : "China",
            "xingtai" : "China",
            "shaoguan" : "China",
            "feira de santana" : "Brazil",
            "guixi" : "China",
            "ruijin" : "China",
            "zahedan" : "Iran",
            "jinzhong" : "China",
            "portland" : "United States",
            "jintan" : "China",
            "reynosa" : "Mexico",
            "ilorin" : "Nigeria",
            "oklahoma city" : "United States",
            "nakhon ratchasima" : "Thailand",
            "shangzhou" : "China",
            "panshi" : "China",
            "kerman" : "Iran",
            "kaiyuan" : "China",
            "islamabad" : "Pakistan",
            "sarajevo" : "Bosnia and Herzegovina",
            "bikaner" : "India",
            "dushanbe" : "Tajikistan",
            "vientiane" : "Laos",
            "dehradun" : "India",
            "zhangshu" : "China",
            "beining" : "China",
            "abu dhabi" : "United Arab Emirates",
            "shimkent" : "Kazakhstan",
            "xingcheng" : "China",
            "imbaba" : "Egypt",
            "yicheng" : "China",
            "skoplje" : "Macedonia",
            "kadhimain" : "Iraq",
            "dali" : "China",
            "fuding" : "China",
            "jinzhou" : "China",
            "renhuai" : "China",
            "kemerovo" : "Russia",
            "duisburg" : "Germany",
            "rasht" : "Iran"
        }